github-repo: "https://github.com/spring-io/start.spring.io.git"
github-repo-name: "spring-io/start.spring.io"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "master"
build-name: "initializr"
pipeline-name: "start-site"
concourse-url: "https://ci.spring.io"
google-analytics-tracking-code: "GTM-KZM7GF6"